openapi: 3.1.0
info:
  title: OCPI 2.3.0 - Commands Module - Sender Interface
  description: |
    The Sender Interface (typically implemented by the eMSP) receives asynchronous
    command results from the CPO.
  version: 2.3.0
  contact:
    name: EVRoaming Foundation
    url: https://evroaming.org
externalDocs:
  description: OCPI 2.3.0 Specification
  url: https://github.com/ocpi/ocpi/blob/master/mod_commands.asciidoc
security:
  - OCPIToken: []

paths:
  /commands/{uid}:
    post:
      operationId: senderPostCommandResult
      summary: Receive asynchronous command result
      tags: [ Commands ]
      description: |
        The MSP receives the asynchronous result of a previously sent command.
        The URL to this endpoint is provided in the response_url field of each command request.
        The path shown here is a typical implementation pattern.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - in: path
          name: uid
          description: Unique ID relating to the original command request.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/CommandResult"
      responses:
        "200":
          $ref: "../../components/schema.yaml#/components/responses/OCPISuccessResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
